apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: drkiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkiq
      component: redis
  template:
    metadata:
      labels:
        app: drkiq
        component: redis
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
           claimName: redis
      containers:
      - name: name
        image: redis:5-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/var/lib/redis/data"
          name: data
